apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8
          name: mysql
          args:
            - '--default-authentication-plugin=mysql_native_password'
          env:
            - name: MYSQL_DATABASE
              value: 'oncoreport'
            - name: MYSQL_USER
              value: 'oncoreport'
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'no'
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oncoreport
                  key: mysql_password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oncoreport
                  key: mysql_password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim
